### ISSUE TITLE
Missing or malformed text

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/leo-tolstoy_hadji-murad_aylmer-maude#19]
https://github.com/standardebooks/leo-tolstoy_hadji-murad_aylmer-maude/blob/5a636e2a0cee303430fcad50840d050eab0e6b93/src/epub/text/chapter-3.xhtml#L12

The following sentence is malformed and doesn't parse:

"Vorontsóv's wife, Márya Vasilevna, a famous Petersberg beauty..."

It should be:

"Vorontsóv lived with his wife, Márya Vasilevna, a famous Petersberg beauty..."

See: https://www.google.com/books/edition/The_Complete_Works_of_Count_Tolstoy_Hadj/CfnqYpnFuTMC?hl=en&gbpv=1&dq=hadji+murat&pg=PA19&printsec=frontcover

**Comment by acabal** [comment]
Thanks, this is fixed now!
